### ISSUE TITLE
Static files cause error during freezing after switching to Python 3

### ISSUE THREAD

**Issue by Markus00000** [SimonSapin/Frozen-Flask#52] opened 2015-08-04 18:24 UTC
After switching to Python 3 this error occurs for every file in `/static/`:

    Traceback (most recent call last):
      File "site.py", line 621, in <module>
        freezer.freeze()
      File "/home/me/dev/site/lib/python3.4/site-packages/flask_frozen/__init__.py", line 149, in freeze
        new_filename = self._build_one(url)
      File "/home/me/dev/site/lib/python3.4/site-packages/flask_frozen/__init__.py", line 257, in _build_one
        base_url=base_url)
      File "/home/me/dev/site/lib/python3.4/site-packages/werkzeug/test.py", line 774, in get
        return self.open(*args, **kw)
      File "/home/me/dev/site/lib/python3.4/site-packages/flask/testing.py", line 108, in open
        follow_redirects=follow_redirects)
      File "/home/me/dev/site/lib/python3.4/site-packages/werkzeug/test.py", line 742, in open
        response = self.run_wsgi_app(environ, buffered=buffered)
      File "/home/me/dev/site/lib/python3.4/site-packages/werkzeug/test.py", line 661, in run_wsgi_app
        self.cookie_jar.extract_wsgi(environ, rv[2])
      File "/home/me/dev/site/lib/python3.4/site-packages/werkzeug/test.py", line 187, in extract_wsgi
        U2Request(get_current_url(environ)),
      File "/usr/lib64/python3.4/urllib/request.py", line 266, in __init__
        self.full_url = url
      File "/usr/lib64/python3.4/urllib/request.py", line 292, in full_url
        self._parse()
      File "/usr/lib64/python3.4/urllib/request.py", line 321, in _parse
        raise ValueError("unknown url type: %r" % self.full_url)
    ValueError: unknown url type: ':///static/zipped.zip'

I am using this setting:

    app.config['FREEZER_BASE_URL'] = '/'

Not setting `FREEZER_BASE_URL` resolves the error.

I tried the current git version of Frozen-Flask with the same result.

**Comment by SimonSapin** [comment] 2015-08-05 07:25
Please provide a minimal test case to reproduce the issue.

**Comment by Markus00000** [comment] 2015-08-05 07:36
Make sure `/static/` exists and touch a file in there:

    mkdir static
    touch static/zippy.zip

Minimal example:

    from flask import Flask
    from flask_frozen import Freezer
    
    app = Flask(__name__)
    freezer = Freezer(app)
    
    app.config['FREEZER_BASE_URL'] = '/'
    
    
    @app.route('/')
    def hello_world():
        return 'Hello World!'
    
    
    if __name__ == '__main__':
        freezer.freeze()
        #app.run()

**Comment by SimonSapin** [comment] 2015-08-05 13:43
I don’t know why Python 3 behaves differently from Python 2 here (still looking into it), but `FREEZER_BASE_URL` is intended to be an absolute URL like `app.config['FREEZER_BASE_URL'] = 'https://example.net/'`. What are you trying to do by setting it to `/` ? Would leaving it unset work?

**Comment by SimonSapin** [comment] 2015-08-05 13:53
I think the difference is in [`werkzeug.wsgi.get_current_url`](http://werkzeug.pocoo.org/docs/0.10/wsgi/#werkzeug.wsgi.get_current_url), so outside of my control. When given a WSGI environment (which represents a simulated HTTP request) with an empty string for `HTTP_HOST`, it returns `/` on Python 2 and something like `:///static/a.zip` on Python 3.

Maybe there is an issue to fix in WerkZeug… but maybe just don’t give a relative base URL?

**Comment by Markus00000** [comment] 2015-08-05 15:02
I’m not sure whether I remember this correctly as the base URL setting entered my code three years ago in the initial commit.

I think I set it to `/` as I wanted to use the same frozen version locally and on a remote server and ended up with broken URLs (possibly caused by different setups). Setting the base URL to `/` made it work on both ends.

I just checked and in my current setup the base URL doesn’t need to be set.

If you don’t see any use in `/` as a base URL, it was probably just a bad setup or misunderstanding on my side.

Thanks a lot for your help!

**Comment by SimonSapin** [comment] 2015-08-05 15:13
To be honest I don’t remember all the details as I also wrote this code a few years ago :) According to https://pythonhosted.org/Frozen-Flask/#configuration , the host part of `FREEZER_BASE_URL` is only relevant if you use `url_for(…, _external=True)`, and the default is `http://localhost/`.

**Comment by SimonSapin** [comment] 2015-08-06 03:24
> I just checked and in my current setup the base URL doesn’t need to be set.

Closing as it sounds like you found something that works for you. Feel free to reopen.

**Closed by SimonSapin** 2015-08-06 03:24 UTC
